name: quds_ui_kit
description: Flutter UI kit [animating icons, buttons, texts, counter, digital clock) - page transitions - toasts - dialogs-  pagination - splash screen ...etc ]
version: 0.0.4
repository: https://github.com/MohammedAsaadAsaad/quds_ui_kit
homepage: https://www.alrazysoft.com

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter